function obj = calc_total_impacts(obj)

obj.value = obj.value_glider +...
    obj.value_powertrain +...
        obj.value_energy_storage +...
        obj.value_energy_chain +...
        obj.value_maintenance +...
        obj.value_EoL +...
        obj.value_road +...
        obj.value_direct_non_exhaust +...
        obj.value_direct_exhaust;


end

